#ifndef __TETRIS_CUSTOME_EVENT
#define __TETRIS_CUSTOME_EVENT

#include <wx/event.h>
DECLARE_EVENT_TYPE(wxEVT_TETRIS_EVENT,wxID_ANY)
DECLARE_EVENT_TYPE(wxEVT_GAMEHALL_EVENT,wxID_ANY)
DECLARE_EVENT_TYPE(wxEVT_BOARD_EVENT,wxID_ANY)


#endif